add_frame_idx: true
exp_name: egoschema_full
max_frame: 8
model_name: gpt-4.1-2025-04-14
save_img: false
select2: ./outputs/egoschema_full/select2.yml
uniform_sample: false
uniform_target: step1
use_anno: false
use_cont: false
use_cot: true
use_crop: false



