add_frame_idx: true
exp_name: exp0629_egoschema_verify2
max_frame: 8
model_name: gpt-4.1-2025-04-14
save_img: true
select2: ./outputs/exp0629_egoschema/select2.yml
uniform_sample: false
uniform_target: step1
use_anno: false
use_cont: false
use_cot: true
use_crop: false



