egoschema:
  frame_fps: 1
  num_examples_to_run: 5
  video_path: D:/datasets/egoschema/videos
  # anno_path: D:/datasets/LLoVi_caption/egoschema/subset_anno.json 
  anno_path: D:/datasets/egoschema/questions.json
  subset_path: D:/datasets/egoschema/subset_answers.json

nextoe:
  frame_fps: 1
  num_examples_to_run: 100
  map_path: D:/datasets/nextqa/map_vid_vidorID.json
  video_path: D:/datasets/nextqa/NExTVideo
  anno_path: D:/datasets/nextqa/OE
  stopwords_path: D:/datasets/nextqa/stopwords.csv

nextmc:
  frame_fps: 1
  num_examples_to_run: 1000
  stopwords_path: D:/datasets/nextqa/stopwords.csv
  map_path: D:/datasets/nextqa/map_vid_vidorID.json
  video_path: D:/datasets/nextqa/NExTVideo
  anno_path: D:/datasets/nextqa/MC