select: ./outputs/exp0711_egoschema_full/select.yml
model_name: gpt-4.1-2025-04-14
max_frame: 48
exp_name: exp0711_egoschema_full
# use_crop: false
use_crop: true
question_only: true

# unfirom sample frames, with num equals step1 output
# uniform_sample: false 
uniform_sample: true