- name: mvbench_test
  test_rate: 1
  eval_rate: 0

- name: egoschema_subset
  answer_path: D:\work\实时对话\TET\outputs\qwenvl_test3\answer.jsonl
  test_rate: 0.3
  eval_rate: 0.1

- name: nextmc_test
  answer_path: D:\work\实时对话\TET\outputs\qwenvl_test_nextmc\answer.jsonl
  test_rate: 0.3
  eval_rate: 0.1

# - name: videomme_long
#   answer_path: D:\work\实时对话\TET\outputs\qwenvl_test_videomme_long\answer.jsonl
#   test_rate: 0.3
#   eval_rate: 0.1

# - name: videomme_medium
#   answer_path: D:\work\实时对话\TET\outputs\qwenvl_test_videomme_medium\answer.jsonl
#   test_rate: 0.3
#   eval_rate: 0.1

- name: videomme_short
  answer_path: D:\work\实时对话\TET\outputs\qwenvl_test_videomme_short\answer.jsonl
  test_rate: 0.3
  eval_rate: 0.1

- name: intentqa_test
  answer_path: D:\work\实时对话\TET\outputs\qwenvl_test_intentqa\answer.jsonl
  test_rate: 0.3
  eval_rate: 0.1

- name: mlvu_test
  answer_path: D:\work\实时对话\TET\outputs\qwenvl_test_mlvu\answer.jsonl
  test_rate: 0.3
  eval_rate: 0.1

